# Generated by Django 4.0.4 on 2022-06-09 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buses', '0001_initial'),
        ('principal', '0002_rename_usuario_usuarios'),
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tickets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.CharField(max_length=80)),
                ('buses_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buses.buses')),
                ('rutas_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutas.rutas')),
                ('usuarios_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.usuarios')),
            ],
        ),
    ]
