# Generated by Django 4.0.4 on 2022-06-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('placa', models.CharField(max_length=80)),
                ('tipo', models.CharField(max_length=80)),
                ('numero_de_puestos', models.CharField(max_length=80)),
            ],
        ),
    ]
